import { Link, NavLink, useNavigate } from 'react-router-dom'
import { BarChart3, Bell, ClipboardList, LayoutDashboard, LogOut, Moon, Search, Settings, Sun, UserRound } from 'lucide-react'
import { useAuth } from '../context/AuthContext'
import { useLocationContext } from '../context/LocationContext'
import { useTheme } from '../context/ThemeContext'

const links = [["/dashboard", "Dashboard", LayoutDashboard], ["/patients", "Pasien", ClipboardList], ["/reports", "Laporan", BarChart3], ["/profile", "Profil", UserRound], ["/settings", "Pengaturan", Settings]]

export default function AppLayout({ children }) {
  const { user, logout } = useAuth(); const { currentLocation, setCurrentLocation } = useLocationContext(); const { theme, toggleTheme } = useTheme(); const navigate = useNavigate()
  const handleLogout = async () => { await logout(); navigate('/login') }
  return <div className="app-shell"><aside className="sidebar"><Link to="/dashboard" className="brand"><span className="brand-mark">+</span><strong>SehatKu<small>Kelola Data Kesehatan</small></strong></Link><nav>{links.map(([to, label, Icon]) => <NavLink key={to} to={to} className={({ isActive }) => isActive ? 'nav-link active' : 'nav-link'}><Icon size={17} />{label}</NavLink>)}</nav><div className="sidebar-footer"><button className="nav-link" onClick={handleLogout}><LogOut size={17} />Keluar</button></div></aside><main className="main-content"><header className="topbar"><div className="mobile-menu"><span>☰</span></div><div className="topbar-title"><span className="topbar-mobile-logo">+</span><div><span className="eyebrow">Ruang kesehatan sekolah</span><h1>{window.location.pathname === '/dashboard' ? 'Dashboard' : links.find(([to]) => window.location.pathname.startsWith(to))?.[1] || 'SehatKu'}</h1></div></div><div className="topbar-actions"><label className="search-box"><Search size={15} /><input placeholder="Cari pasien..." aria-label="Cari pasien" /></label><button className="icon-button notification" title="Notifikasi" aria-label="Notifikasi"><Bell size={17} /><b>3</b></button><button className="icon-button theme-toggle" onClick={toggleTheme} title="Ganti tema" aria-label="Ganti tema">{theme === 'dark' ? <Sun size={17} /> : <Moon size={17} />}</button><div className="user-chip"><span>{(user?.displayName || user?.email || 'A').charAt(0).toUpperCase()}</span><div><strong>{user?.displayName || 'Admin'}</strong><small>Petugas</small></div></div><select className="location-select" aria-label="Pilih lokasi" value={currentLocation} onChange={(event) => setCurrentLocation(event.target.value)}><option value="kamar">Kamar</option><option value="uks">UKS</option></select></div></header>{children}<nav className="mobile-nav">{links.slice(0, 5).map(([to, label, Icon]) => <NavLink key={to} to={to} className={({ isActive }) => isActive ? 'mobile-nav-link active' : 'mobile-nav-link'}><Icon size={16} /><small>{label}</small></NavLink>)}</nav></main></div>
}
