import { useEffect, useMemo, useState } from 'react'
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { collection, onSnapshot, query, where } from 'firebase/firestore'
import { db } from '../firebase'
import { toDate } from '../utils/patientStats'
import { useRealtimeClock } from '../hooks/useRealtimeClock'

export default function Reports() { const [filters, setFilters] = useState({ location: 'all', start: '', end: '' }); const [patients, setPatients] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { setLoading(true); const unsub = onSnapshot(query(collection(db, 'patients'), ...(filters.location === 'all' ? [] : [where('location', '==', filters.location)])), (snap) => { setPatients(snap.docs.map((item) => ({ id: item.id, ...item.data() }))); setLoading(false) }, (err) => { setError(err.message || 'Gagal memuat laporan'); setLoading(false) }); return () => { unsub(); setLoading(false) } }, [filters.location])
  const { now } = useRealtimeClock()
  const filtered = useMemo(() => patients.filter((patient) => { const date = toDate(patient.createdAt); if (!date) return !filters.start && !filters.end; const value = date.toISOString().slice(0, 10); return (!filters.start || value >= filters.start) && (!filters.end || value <= filters.end) }), [patients, filters.start, filters.end])
  const summary = useMemo(() => { const today = now.toISOString().slice(0, 10); return { total: filtered.length, kamar: filtered.filter((p) => p.location === 'kamar').length, uks: filtered.filter((p) => p.location === 'uks').length, active: filtered.filter((p) => p.status === 'aktif').length, completed: filtered.filter((p) => p.status === 'selesai').length, today: filtered.filter((p) => toDate(p.createdAt)?.toISOString().slice(0, 10) === today).length } }, [filtered, now])
  const chart = [{ name: 'Kamar', pasien: summary.kamar }, { name: 'UKS', pasien: summary.uks }, { name: 'Aktif', pasien: summary.active }, { name: 'Selesai', pasien: summary.completed }]
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">Analitik pasien</span><h2>Laporan</h2></div></div><div className="filter-row"><label>Lokasi<select className="input-field" value={filters.location} onChange={(e) => setFilters({ ...filters, location: e.target.value })}><option value="all">Semua lokasi</option><option value="kamar">Kamar</option><option value="uks">UKS</option></select></label><label>Mulai<input className="input-field" type="date" value={filters.start} onChange={(e) => setFilters({ ...filters, start: e.target.value })} /></label><label>Akhir<input className="input-field" type="date" value={filters.end} onChange={(e) => setFilters({ ...filters, end: e.target.value })} /></label></div>{error && <div className="alert error">{error}</div>}{loading && !patients.length ? <div className="panel">Memuat laporan...</div> : <><div className="report-grid">{[['Total pasien', summary.total], ['Pasien hari ini', summary.today], ['Pasien kamar', summary.kamar], ['Pasien UKS', summary.uks], ['Pasien aktif', summary.active], ['Pasien selesai', summary.completed]].map(([label, value]) => <div className="report-number" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><div className="panel chart-panel"><h3>Distribusi pasien</h3><ResponsiveContainer width="100%" height={300}><BarChart data={chart}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="name" /><YAxis allowDecimals={false} /><Tooltip /><Legend /><Bar dataKey="pasien" fill="var(--md-chart-primary)" radius={[4, 4, 0, 0]} /></BarChart></ResponsiveContainer></div></>}</section> }
