import { useEffect, useState } from 'react'
import { Activity, CheckCircle2, Clock3, Users } from 'lucide-react'
import { getPatientsByLocation } from '../../patientService'
import { useLocationContext } from '../context/LocationContext'
import { getPatientStats } from '../utils/patientStats'

export default function Dashboard() { const { currentLocation } = useLocationContext(); const [patients, setPatients] = useState([]); const [error, setError] = useState('')
  useEffect(() => { setError(''); return getPatientsByLocation(currentLocation, setPatients, setError) }, [currentLocation])
  const stats = getPatientStats(patients); const cards = [['Total Pasien', stats.total, Users], ['Pasien Aktif', stats.active, Activity], ['Pasien Selesai', stats.completed, CheckCircle2], ['Pasien Hari Ini', stats.today, Clock3]]
  return <section className="page dashboard-page"><div className="page-heading"><div><span className="eyebrow">Ringkasan lokasi</span><h2>Dashboard</h2><p>Selamat datang kembali. Berikut ringkasan kesehatan hari ini.</p></div><span className="location-badge">● {currentLocation === 'kamar' ? 'Kamar' : 'UKS'}</span></div>{error && <div className="alert error">{error}</div>}<div className="stat-grid">{cards.map(([label, value, Icon], index) => <article className={`stat-card stat-card-${index + 1}`} key={label}><div className="stat-icon"><Icon size={20} /></div><span>{label}</span><strong>{value}</strong><small>{index === 0 ? 'Semua pasien' : index === 1 ? 'Sedang dirawat' : index === 2 ? 'Sudah selesai' : 'Registrasi baru'}</small></article>)}</div><div className="dashboard-columns"><div className="panel patient-overview"><div className="panel-heading"><div><h3>Pasien sedang dirawat</h3><p className="muted">Daftar pasien aktif di lokasi ini.</p></div><a href="/patients" className="panel-link">Lihat semua</a></div>{patients.filter((patient) => patient.status === 'aktif').slice(0, 5).map((patient) => <div className="patient-row" key={patient.id}><span className="patient-avatar">{patient.name?.charAt(0) || '?'}</span><div><strong>{patient.name}</strong><small>{patient.patientId} · {patient.phone || 'Telepon belum diisi'}</small></div><span className="patient-status">Aktif</span></div>)}{patients.filter((patient) => patient.status === 'aktif').length === 0 && <div className="empty-state">Belum ada pasien aktif di lokasi ini.</div>}</div><div className="panel activity-panel"><div className="panel-heading"><div><h3>Aktivitas terbaru</h3><p className="muted">Perubahan data terakhir.</p></div><span className="status-dot">Live</span></div>{patients.slice(0, 5).map((patient) => <div className="activity-row" key={patient.id}><span className="activity-dot" /><div><strong>{patient.name}</strong><p>{patient.status === 'aktif' ? 'Pasien sedang dirawat' : 'Perawatan selesai'}</p></div></div>)}{patients.length === 0 && <div className="empty-state">Aktivitas akan muncul setelah ada data pasien.</div>}</div></div></section> }
